name: CML
on: [push]
jobs:
  run:
     runs-on: ubuntu-latest
     container: docker://ghcr.io/iterative/cml:0-dvc2-base1
     steps:
        - uses: actions/checkout@v2
        - name: Train model
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            pip install -r requirements.txt
            dvc pull data --run-cache        # Pull data & run-cache from S3
            dvc repro                        # Reproduce pipeline
            cat metrics.txt >> report.md
            cml publish confusion_matrix.png --md >> report.md
            cml send-comment report.md