name: CML
on: [push]
jobs:
  run:
     runs-on: ubuntu-latest
     container: docker://ghcr.io/iterative/cml:0-dvc2-base1
     steps:
        - uses: actions/checkout@v2
        - name: Train model
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          run: |
            git fetch origin main
            pip install -r requirements.txt
            echo "## Confusion Matrix" >> report.md
            cml publish confusion_matrix.png --md >> report.md
            echo "## Metric Diff" >> report.md
            dvc metrics diff main >> report.md
            cml send-comment report.md